# Generated by Django 3.2.7 on 2022-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('views', models.IntegerField()),
                ('is_super_topic', models.BooleanField(default=False)),
                ('is_acive', models.BooleanField(default=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update', models.DateField()),
                ('author', models.TextField(max_length=100)),
                ('number_of_posts', models.IntegerField()),
                ('subject', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=200)),
                ('key', models.TextField(max_length=19)),
                ('number_of_months', models.IntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('text', models.TextField()),
                ('author', models.TextField(max_length=200)),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
