# Generated by Django 3.2.7 on 2022-04-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_app', '0001_initial'),
    ]

    operations = [
    ]
