# Generated by Django 3.2.7 on 2022-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo_app', '0002_auto_20220430_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('email', models.TextField(max_length=150)),
            ],
        ),
    ]
