# Generated by Django 3.1.3 on 2021-03-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
