# Generated by Django 3.1.3 on 2021-03-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
