# Generated by Django 3.1.3 on 2021-03-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0011_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
