# Generated by Django 3.1.3 on 2021-03-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0013_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
