# Generated by Django 3.1.3 on 2021-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0017_auto_20210305_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
