# Generated by Django 3.1.3 on 2021-03-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0018_auto_20210305_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bug_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
    ]
