# Generated by Django 3.1.3 on 2021-03-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0019_auto_20210305_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
