# Generated by Django 3.1.3 on 2021-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0024_auto_20210307_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_report',
            field=models.BooleanField(blank=True),
        ),
    ]
