# Generated by Django 3.1.3 on 2021-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0025_auto_20210307_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bug_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
