# Generated by Django 3.1.3 on 2021-03-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0026_auto_20210307_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
