# Generated by Django 3.1.3 on 2021-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts_app', '0027_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField()),
                ('is_report', models.BooleanField(blank=True)),
                ('bug_type', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
