# Generated by Django 3.1.3 on 2021-01-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_post_day123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='day123',
            field=models.CharField(max_length=200),
        ),
    ]
