# Generated by Django 3.1.3 on 2021-01-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20210105_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='day123',
        ),
    ]
