# Generated by Django 3.2.3 on 2021-06-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0002_resetpasswordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordmodel',
            name='limit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='ForgetPasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
